### ISSUE TITLE
RPG patch #1

### ISSUE THREAD

**Issue by RavenNightingale** [minidevil96/rpg#3]
//Begin menus classifications

//inventory menu UI
INV = {}
INV.pd = new PixelDisplay
INV.sd = new SpriteDisplay

//load inventory on
INV.load = function(model)
    //Prep Screen
    self.pd.clear "#80808089"
    self.sd.clear

    //install displays
    self.pd.install 3
    self.sd.install 2

    //Close button Definition
    close_button = new Sprite
    close_button.image = Image.create(100, 25, color.clear)
    close_button.x = 240 + close_button.image.width /2
    close_button.y = 110 + close_button.image.height /2

    
    inv_menu = true

    //Begin Drawing
    
    self.pd.fillRect 240, 160, 500, 350, color.gray
    

    //Pushes goes here
    self.sd.sprites.push close_button

    

    //set display(1) as text display
    display(1).mode = displayMode.text
    text = display(1)

    //Begin Inventory Loop
    while inv_menu
        if key.pressed("escape") then inv_menu = false
        if key.available then
            pressed = key.get
        end if
        yield
    end while

    //Upon exit clear the inventory from the screen
    self.pd.clear
    self.sd.clear

end function

//Main Menu UI
main = {}
main.pd = new PixelDisplay
main.sd = new SpriteDisplay

//Load Main Menu
main.load_main = function()
    
    
end function

//Load Main Menu Character Creation
main.load_character_creation = function()
    
end function

//please add this to the game_menus.ms. patch to fix PixalDisplay on line 62

**Comment by minidevil96** [comment]
This has been patched. Being pushed to main branch. re-building release package.
